site_name: InfraWatch Documentation
theme:
  name: material

nav:
  - O que é InfraWatch?: docs/introducao.md
  - Como Instalar?: docs/instalacao.md
  - Arquitetura?: docs/arquitetura.md
  - Como Usar: docs/uso.md
  - API: docs/api.md
  - Contribuição: docs/contribuicao.md
  - Roadmap: docs/roadmap.md
  - FAQ: docs/faq.md
